# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('campaign_id', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_info', models.TextField(null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-sent_date'],
                'verbose_name': 'Mailchimp Log',
                'verbose_name_plural': 'Mailchimp Logs',
                'permissions': [('can_view', 'Can view Mailchimp information'), ('can_send', 'Can send Mailchimp newsletters')],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('list_id', models.CharField(max_length=50)),
                ('template_id', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=255)),
                ('to_email', models.EmailField(max_length=254)),
                ('folder_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_opens', models.BooleanField(default=True)),
                ('tracking_html_clicks', models.BooleanField(default=True)),
                ('tracking_text_clicks', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('authenticate', models.BooleanField(default=False)),
                ('google_analytics', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_footer', models.BooleanField(default=False)),
                ('generate_text', models.BooleanField(default=False)),
                ('auto_tweet', models.BooleanField(default=False)),
                ('segment_options', models.BooleanField(default=False)),
                ('segment_options_all', models.BooleanField()),
                ('segment_options_conditions', models.TextField()),
                ('type_opts', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_info', models.TextField(null=True)),
                ('locked', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Reciever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recievers', to='mailchimp.Campaign')),
            ],
        ),
    ]
